let sitatEl = document.getElementById("idSitat");
let decifrerEl = document.getElementById("idDecifrer");

decifrerEl.addEventListener("click",decifrerFunk);

    
let krypteringene = [
    {
        bokstav:"a",
        kryptering:"q",
    }
    ,
    {
        bokstav:"A",
        kryptering:"Q",
    }
    ,
    {
        bokstav:"b",
        kryptering:"w",
    }
    ,
    {
        bokstav:"B",
        kryptering:"W",
    }
    ,
    {
        bokstav:"c",
        kryptering:"e",
    }
    ,
    {
        bokstav:"C",
        kryptering:"E",
    }
    ,
    {
        bokstav:"d",
        kryptering:"r",
    }
    ,
    {
        bokstav:"D",
        kryptering:"R",
    }
    ,
    {
        bokstav:"e",
        kryptering:"t",
    }
    ,
    {
        bokstav:"E",
        kryptering:"T",
    }
    ,
    {
        bokstav:"f",
        kryptering:"y",
    }
    ,
    {
        bokstav:"F",
        kryptering:"Y",
    }
    ,
    {
        bokstav:"g",
        kryptering:"u",
    }
    ,
    {
        bokstav:"G",
        kryptering:"U",
    }
    ,
    {
        bokstav:"h",
        kryptering:"i",
    }
    ,
    {
        bokstav:"H",
        kryptering:"I",
    }
    ,
    {
        bokstav:"i",
        kryptering:"o",
    }
    ,
    {
        bokstav:"I",
        kryptering:"O",
    }
    ,
    {
        bokstav:"j",
        kryptering:"p",
    }
    ,
    {
        bokstav:"J",
        kryptering:"P",
    }
    ,
    {
        bokstav:"k",
        kryptering:"å"
    }
    ,
    {
        bokstav:"K",
        kryptering:"Å",
    }
    ,
    {
        bokstav:"l",
        kryptering:"a",
    }
    ,
    {
        bokstav:"L",
        kryptering:"A",
    }
    ,
    {
        bokstav:"m",
        kryptering:"s",
    }
    ,
    {
        bokstav:"M",
        kryptering:"S",
    }
    ,
    {
        bokstav:"n",
        kryptering:"d",
    }
    ,
    {
        bokstav:"N",
        kryptering:"D",
    }
    ,
    {
        bokstav:"o",
        kryptering:"f",
    }
    ,
    {
        bokstav:"O",
        kryptering:"F",
    }
    ,
    {
        bokstav:"p",
        kryptering:"g",
    }
    ,
    {
        bokstav:"P",
        kryptering:"G",
    }
    ,
    {
        bokstav:"q",
        kryptering:"h",
    }
    ,
    {
        bokstav:"Q",
        kryptering:"H",
    }
    ,
    {
        bokstav:"r",
        kryptering:"j",
    }
    ,
    {
        bokstav:"R",
        kryptering:"J",
    }
    ,
    {
        bokstav:"s",
        kryptering:"k",
    }
    ,
    {
        bokstav:"S",
        kryptering:"K",
    }
    ,
    {
        bokstav:"t",
        kryptering:"l",
    }
    ,
    {
        bokstav:"T",
        kryptering:"L",
    }
    ,
    {
        bokstav:"u",
        kryptering:"ø",
    }
    ,
    {
        bokstav:"U",
        kryptering:"Ø",
    }
    ,
    {
        bokstav:"v",
        kryptering:"æ",
    }
    ,
    {
        bokstav:"V",
        kryptering:"Æ",
    }
    ,
    {
        bokstav:"w",
        kryptering:"z",
    }
    ,
    {
        bokstav:"W",
        kryptering:"Z",
    }
    ,
    {
        bokstav:"x",
        kryptering:"x",
    }
    ,
    {
        bokstav:"X",
        kryptering:"X",
    }
    ,
    {
        bokstav:"y",
        kryptering:"c",
    }
    ,
    {
        bokstav:"Y",
        kryptering:"C",
    }
    ,
    {
        bokstav:"z",
        kryptering:"v",
    }
    ,
    {
        bokstav:"Z",
        kryptering:"V",
    }
    ,
    {
        bokstav:"æ",
        kryptering:"b",
    }
    ,
    {
        bokstav:"Æ",
        kryptering:"B",
    }
    ,
    {
        bokstav:"ø",
        kryptering:"n",
    }
    ,
    {
        bokstav:"Ø",
        kryptering:"N",
    }
    ,
    {
        bokstav:"å",
        kryptering:"m",
    }
    ,
    {
        bokstav:"Å",
        kryptering:"M",
    }
    ,
]


function decifrerFunk(){
    document.getElementById('idOutput').innerHTML =""

    for (let i = 0; i < sitatEl.value.length; i++) {
        let n = 0
        while (krypteringene[n].bokstav != sitatEl.value[i] ){
        n++
        }
        document.getElementById('idOutput').innerHTML += krypteringene[n].kryptering ;
        
    }}
    